apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- cronjob-deployment.yaml
- postgres-external.yaml

configMapGenerator:
- files:
  - config.yaml
  name: {{APP_NAME}}-config
generatorOptions:
  disableNameSuffixHash: true

labels:
- pairs:
    app.kubernetes.io/part-of: {{APP_NAME}}
  fields:
  - path: metadata/labels
    create: true
  - path: spec/selector/matchLabels
    create: true
    group: apps
    kind: Deployment
  - path: spec/template/metadata/labels
    create: true
    group: apps
    kind: Deployment
  - path: spec/selector
    create: false
    version: v1
    kind: Service
