apiVersion: v1
kind: Secret
metadata:
  name: evm-scan-secret
  namespace: web3-analyse
type: Opaque
stringData:
  secret.yaml: |
    # 此文件会被 overlay 中的 secret.yaml 替换
    # 敏感信息请勿提交到 Git
    # dev 环境会自动更新，prod 环境需手动配置
