apiVersion: v1
kind: Service
metadata:
  name: evm-scan-web
  namespace: web3-analyse
  labels:
    app: evm-scan-web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: evm-scan-web
