apiVersion: apps/v1
kind: Deployment
metadata:
  name: evm-scan-cronjob
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: evm-scan-cronjob
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
