apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}-web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: {{APP_NAME}}-web
          env:
            - name: SECRET_FILE
              value: "secret.yaml"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
