apiVersion: apps/v1
kind: Deployment
metadata:
  name: evm-scan-cronjob
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: evm-scan-cronjob
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
