apiVersion: apps/v1
kind: Deployment
metadata:
  name: evm-scan-scanner
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: evm-scan-scanner
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
