apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: {{APP_NAME}}-web
  newName: {{HARBOR_REGISTRY}}/{{HARBOR_PROJECT}}
  newTag: web-latest
- name: {{APP_NAME}}-job
  newName: {{HARBOR_REGISTRY}}/{{HARBOR_PROJECT}}
  newTag: job-latest
- name: {{APP_NAME}}-cronjob
  newName: {{HARBOR_REGISTRY}}/{{HARBOR_PROJECT}}
  newTag: cronjob-latest
